// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 25
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){
var __dee;(function(){(function(a){__dee=a;__dee.a="dee";__dee.b=[];__dee.c=!0})(function(){var a=!1;return a?"gtm.sync":"gtm.js"})})();

var __c;(function(){(function(a){__c=a;__c.a="c";__c.b=["google"];__c.c=!0})(function(a){return a["44"]})})();var __e;(function(){(function(a){__e=a;__e.a="e";__e.b=["google"];__e.c=!0})(function(){return Ca})})();




var __u;(function(){(function(a){__u=a;__u.a="u";__u.b=["google"];__u.c=!0})(function(a){var b;b=(b=a[""]?a[""]:S("gtm.url",1))||ca();var c=a["42"],d;if(c&&"URL"!=c){var e=T(String(b));d=U(e,c,"HOST"==c?a[""]:void 0,"PATH"==c?a[""]:void 0,"QUERY"==c?a[""]:void 0)}else d=Da(T(String(b)));return d})})();
var __ctto;(function(){(function(a){__ctto=a;__ctto.a="ctto";__ctto.b=[];__ctto.c=!0})(function(){var a=q("dataLayer"),b=a&&a.hide;if(!b)return!1;var c=Ha.f,d=!!K.querySelector("body");return null===b.end&&d&&!0===b[c]})})();
var __gthc;(function(){(function(a){__gthc=a;__gthc.a="gthc";__gthc.b=[];__gthc.c=!0})(function(a){var b=q("gaData",{});if(Oa("false")){var c=a["43"];return b[c]&&b[c].hitcount?b[c].hitcount:0}return-1})})();









/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Gb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Hb=function(a){if(null==a)return String(a);var b=Gb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ib=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},La=function(a){if(!a||"object"!=Hb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ib(a,"constructor")&&!Ib(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ib(a,b)},V=function(a,b){var c=b||("array"==Hb(a)?[]:{}),d;for(d in a)if(Ib(a,d)){var e=a[d];"array"==Hb(e)?("array"!=Hb(c[d])&&(c[d]=[]),c[d]=V(e,c[d])):La(e)?(La(c[d])||(c[d]={}),c[d]=V(e,c[d])):c[d]=e}return c};var Ha={},sb=null,Jb=Math.random();Ha.f="GTM-W69N8TP";var Kb=null,Ca=null,jb=!1,Lb="//www.googletagmanager.com/a?id="+Ha.f+"&cv=25",Mb={},Nb={},kb={};var Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,Za,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,$a,Kd,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,
Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf;
(function(){var a=function(a){return{toString:function(){return a}}};Ob=a("");Pb=a("0");Qb="1";Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("4");$b=a("5");ac=a("");bc=a("");cc=a("");
dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");
rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("6");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("7");Gc=a("8");Hc=a("");
Ic=a("9");Jc=a("10");Kc=a("11");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");
Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");
od=a("");pd=a("");qd=a("");rd=a("");sd=a("13");td=a("12");ud=a("16");vd=a("15");wd=a("");xd=a("");yd=a("");Za=a("17");zd=a("");Ad=a("45");Bd=a("46");Cd=a("");Dd=a("18");
Ed=a("19");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");$a=a("20");Kd=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("21");Xd=a("");
Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("22");fe=a("23");ge=a("");he=a("");ie=a("");je=a("24");ke=a("25");le=a("");me=a("27");ne=a("");oe=a("");pe=a("");qe=a("");
re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");
Ke=a("");Le=a("29");Me=a("");Ne=a("");Oe=a("");Pe=a("31");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("32");Ze=
a("33");$e=a("34");af=a("35");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("36");of=a("37");pf=a("");
qf=a("");rf=a("");sf=a("");tf=a("38");uf=a("");vf="39";wf=a("");xf=a("");yf=a("");zf=a("");Af=a("");Bf=a("");Cf=a("");Df=a("");Ef=a("");Ff=a("");Gf=a("");Hf=
a("40");If=a("");Jf=a("");Kf=a("");Lf=a("")})();var Fb=function(a,b){V(a,b)},Mf=function(){},R=function(a){return"function"==typeof a},ab=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Nf=function(a){return"number"==Hb(a)&&!isNaN(a)},Of=function(a){return/^[0-9]+$/.test(a)},nb=function(a){return"string"==Hb(a)},Pf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Qf=function(a,b){if(a&&ab(a)&&0!=a.length)for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Ba=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},W=function(a){return Math.round(Number(a))||0},Oa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Rf=function(a){var b=[];if(ab(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Y=function(){return new Date},Ga=function(a,b){if(!Nf(a)||!Nf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Sf=function(){this.prefix="gtm.";this.values={}};
Sf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Sf.prototype.get=function(a){return this.values[this.prefix+a]};Sf.prototype.contains=function(a){return void 0!==this.get(a)};
var Tf=function(a,b,c){try{if(!a[$d])return a[Za](a,b||Mf,c||Mf);c&&c()}catch(d){}return!1},Uf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ba(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Vf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Wf=function(a){var b=Ha.f;return function(){return a(b)}},Xf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ka=function(){return"gtm"+Yf()},
Yf=function(){var a=sb.sequence||0;sb.sequence=a+1;return a},Na=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Zf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},$f=function(a,b){0==b?a.hc=!0:a.la=!0;var c=a.i;a.G&&(a.G.yb[c]=b);Mb[c]&&(Mb[c].state=b)},ag=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},bg=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var y=window,K=document,fg=navigator,hb=function(a,b){var c=y[a];y[a]=void 0===c?b:c;return y[a]},ib=function(a,b,c,d){return(d||"http:"!=y.location.protocol?a:b)+c},gg=function(a){var b=K.getElementsByTagName("script")[0]||K.body||K.head;b.parentNode.insertBefore(a,b)},ub=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=K.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;ub(d,b);c&&(d.onerror=c);gg(d);return d},Xa=function(a,b){var c=K.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";gg(c);ub(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},va=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},ra=function(a,b,c,d){a.removeEventListener?
a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){y.setTimeout(a,0)},hg=!1,ig=[],jg=function(a){if(!hg){var b=K.createEventObject,c="complete"==K.readyState,d="interactive"==K.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){hg=!0;for(var e=0;e<ig.length;e++)w(ig[e])}ig.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},kg=0,lg=function(){if(!hg&&140>kg){kg++;try{K.documentElement.doScroll("left"),jg()}catch(a){y.setTimeout(lg,
50)}}},ha=function(a){var b=K.getElementById(a);if(b&&za(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(za(document.all[a][c],"id")==a)return document.all[a][c];return b},za=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},mg=function(a){return a.target||a.srcElement||{}},Aa=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},zb=function(a){var b=
K.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ng=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;var f=a;for(e=0;f&&e<=c;e++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},og=!1,pg=[],qg=function(){if(!og){og=!0;for(var a=0;a<pg.length;a++)w(pg[a])}},rg=function(a){a=a||y;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},tb=function(a){window.console&&
window.console.log&&window.console.log(a)};var sg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},U=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||y.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||y.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:y.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Pf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=sg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Da=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},T=function(a){var b=K.createElement("a");a&&(b.href=a);return b};var wa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ob=function(a){return encodeURIComponent(a)},ea=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=U(T(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var P=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Ia=function(a,b){V(a,b)},Pa=function(a){return W(a)},Ab=function(a,b){return Pf(a,b)};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var ug={event:function(a){var b=a[1];if(nb(b)&&!(3<a.length)){var c;if(2<a.length){if(!La(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=V(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&La(a[1])?b=V(a[1],void 0):3==a.length&&nb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var vg=new Sf,wg={},yg={set:function(a,b){V(xg(a,b),wg)},get:function(a){return Z(a,2)},reset:function(){vg=new Sf;wg={}}},Z=function(a,b){return 2!=b?vg.get(a):zg(a)},zg=function(a){for(var b=a.split("."),c=0,d=wg.eventModel;void 0!==d&&c<b.length;c++){if(null===d)return!1;d=d[b[c]]}if(void 0!==d||1<c)return d;var e=wg;for(c=0;c<b.length;c++){if(null===e)return!1;if(void 0===e[b[c]])return;e=e[b[c]]}return e},Ag=function(a,b){vg.set(a,b);V(xg(a,b),wg)},xg=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Bg=!1,Cg=!1;var Dg=Math.random(),Eg="0.050000">Dg;
var Fg=function(a,b){if(Eg){var c=Lb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",Y().getTime()-W(Kb));c+="&sr=0.050000";d("&ps=",Dg);d("&cb=",Ga());G(c)}},Gg=Mf,Hg=function(){var a=!1;
};var Jg=function(a){var b=sb.zones;return b?b.checkState(Ha.f,a):Ig},qb=function(a){var b=sb.zones;!b&&a&&(b=sb.zones=a());return b},Ig={active:!0,isWhitelisted:function(){return!0}};var Kg=Mf,Lg=[],Mg=!1,Ng=function(a){return y["dataLayer"].push(a)},Og=function(a){var b=!1;return function(){!b&&R(a)&&w(Wf(a));b=!0}},Xg=function(){for(var a=!1;!Mg&&0<Lg.length;){Mg=!0;delete wg.eventModel;var b=Lg.shift();if(R(b))try{b.call(yg)}catch(Ma){}else if(ab(b))a:{var c=b;if(nb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=wg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ma){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&nb(l[0])){var m=ug[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Mg=!1;continue}}var n=void 0,p=void 0,r=b,t=r._clear;for(p in r)r.hasOwnProperty(p)&&"_clear"!==p&&(t&&Ag(p,void 0),Ag(p,r[p]));var v=!1,z=r.event;if(z){r.hasOwnProperty("gtm.uniqueEventId")||(r["gtm.uniqueEventId"]=Yf(),Ag("gtm.uniqueEventId",r["gtm.uniqueEventId"]));n=r["gtm.uniqueEventId"];Ca=z;var J=Jg(n);if(J.active){var F=Og(r.eventCallback),E=r.eventTimeout;
E&&y.setTimeout(F,Number(E));v=Kg(n,z,J.isWhitelisted,F,r.eventReporter)}}Kb||(Kb=r["gtm.start"])&&Gg();var L,B=r,D=n,A=z,C=wg;Ca=null;a=v||a}Mg=!1}return!a},Yg=function(){var a=Xg();try{var b=y["dataLayer"].hide;if(b&&void 0!==b[Ha.f]&&b.end){b[Ha.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Zg=function(){var a=hb("dataLayer",[]),b=hb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ig.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});pg.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Lg.push.apply(Lg,b);300<this.length;)this.shift();return Xg()};Lg.push.apply(Lg,a.slice(0));w(Yg)};var $g,ah,bh;
var Ea=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||za(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};if(b&&dh)if("LINK_CLICK"==b)c["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d}c.hasOwnProperty("gtm.elementUrl")||(c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"");return c},sh=
function(a){sb.hasOwnProperty("autoEventsSettings")||(sb.autoEventsSettings={});var b=sb.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},pa=function(a,b,c){sh(a)[b]=c},gb=function(a,b,c,d){var e=sh(a),f=Na(e,b,d);e[b]=c(f)},ta=function(a,b,c){var d=sh(a);return Na(d,b,c)},qa=function(a){return!!ta(a,"init",!1)},ua=function(a){pa(a,"init",!0)},th=function(){};var uh=/(^|\.)doubleclick\.net$/i,vh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Fa=function(a,b,c){for(var d=String(b||K.cookie).split(";"),e=[],f=0;f<d.length;f++){var g=d[f].split("="),h=Ba(g[0]);if(h&&h==a){var k=Ba(g.slice(1).join("="));k&&!1!==c&&(k=decodeURIComponent(k));e.push(k)}}return e},xh=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?wh():[d||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=c;if(uh.test(y.location.hostname)||"/"==n&&vh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=K.cookie;K.cookie=l;if(p!=K.cookie||0<=Pf(Fa(a),b))return!0}return!1},yh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},zh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},wh=function(){var a=U(y.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var fa=function(a){var b=K;return Ah?b.querySelectorAll(a):null},Bh=!1;if(K.querySelectorAll)try{var Ch=K.querySelectorAll(":root");Ch&&1==Ch.length&&Ch[0]==K.documentElement&&(Bh=!0)}catch(a){}var Ah=Bh;var Dh=function(a){for(var b=[],c=K.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var g=[];if(!b||0==b.length)return g;for(var h=0;h<b.length;h++){var k=b[h].split(".");3==k.length&&"GCL"==k[0]&&k[1]&&g.push(k[2])}return g};var Eh=/^\w+$/,Fh=/^[\w-]+$/,Gh=/^\d+\.fls\.doubleclick\.net$/;function Hh(a){return a&&"string"==typeof a&&a.match(Eh)?a:"_gcl"}function Ih(a){if(a){if("string"==typeof a){var b=Hh(a);return{ma:b,ka:b}}if(a&&"object"==typeof a)return{ma:Hh(a.dc),ka:Hh(a.aw)}}return{ma:"_gcl",ka:"_gcl"}}function Jh(a){var b=T(y.location.href),c=U(b,"host",!1);if(c&&c.match(Gh)){var d=U(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Kh(a){return a.filter(function(a){return Fh.test(a)})}var Mh=function(a){var b=Jh("gclaw");if(b)return b.split(".");var c=Ih(a);if("_gcl"==c.ka){var d=Lh();if(d&&(null==d.L||"aw.ds"==d.L))return[d.pa]}return Kh(Dh(c.ka+"_aw"))},Nh=function(a){var b=Jh("gcldc");if(b)return b.split(".");var c=Ih(a);if("_gcl"==c.ma){var d=Lh();if(d&&("ds"==d.L||"aw.ds"==d.L))return[d.pa]}return Kh(Dh(c.ma+"_dc"))};
function Lh(){var a=T(y.location.href),b=U(a,"query",!1,void 0,"gclid"),c=U(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=U(a,"fragment");b=b||sg(d,"gclid");c=c||sg(d,"gclsrc")}return void 0!==b&&b.match(Fh)?{pa:b,L:c}:null}
var Ya=function(a,b,c){var d=Ih(a);c=c||"auto";b=b||"/";var e=Lh();if(null!==e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.pa].join(".");e.L&&"aw.ds"!=e.L||xh(d.ka+"_aw",h,b,c,g,!0);"aw.ds"!=e.L&&"ds"!=e.L||xh(d.ma+"_dc",h,b,c,g,!0)}},Oh=function(){var a=Jh("gac");if(a)return decodeURIComponent(a);for(var b=[],c=K.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({Ab:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=
0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].Ab]||(g[b[h].Ab]=[]),g[b[h].Ab].push({timestamp:k[1],pa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],r=0;r<p.length;r++)n.push(p[r].pa);n=Kh(n);n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var Ph;a:{Ph="G"}var Qh={"":"n",UA:"u",AW:"a",DC:"d",GTM:Ph},ya=function(a){var b=Ha.f.split("-"),c=b[0].toUpperCase();return(Qh[c]||"i")+"3g"+(a&&"GTM"===c?b[1]:"")};var lb=new String("undefined"),Uh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===lb?b:a[d]);return c.join("")}};Uh.prototype.toString=function(){return this.resolve("undefined")};Uh.prototype.valueOf=Uh.prototype.toString;var Vh={},Wh=function(a,b){var c=Yf();Vh[c]=[a,b];return c},Xh=function(a){var b=a?0:1;return function(a){var c=Vh[a];if(c&&R(c[b]))c[b]();Vh[a]=void 0}};var Yh={},Zh,$h;
var ii=function(){};var bb=function(a,b,c,d){va(a,b,c,d)},ka=function(a,b){return y.setTimeout(a,b)},ba=function(a,b,c){u(a,b,c)},db={},Sa=function(a,b,c){var d=db[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.wb:a.cb,d=0;d<c.length;d++)y.setTimeout(c[d],0)}};d={status:1,wb:[],cb:[],ec:void 0};d.qd=u(a,e(d,2),e(d,3));db[a]=d}0===d.status&&(d.ec(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.wb.push(b),c&&d.cb.push(c))},qi=function(a,b){db[a]={status:0,
wb:[],cb:[],ec:b,qd:null}},ca=function(){return y.location.href},cb=function(a){return U(T(a),"fragment")},S=function(a,b){return Z(a,b||2)},na=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Ng(a)},aa=function(a,b){y[a]=b},q=function(a,b,c){var d=y;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},eb=function(a,b){return ng(a,b,100)},x=function(a,b,c,d){var e=!d&&"http:"==y.location.protocol;e&&(e=2!==pb());return(e?b:a)+c},vb=function(a){hg?a():ig.push(a)};
var ia=function(a){var b=0;return b},Cb=function(a){},ja=function(a){var b=!1;return b},fb=function(a,b){return Qf(a,
b)},oa=function(a,b,c,d){gb(a,b,c,d)},sa=function(a,b,c){return ta(a,b,c)};
var Eb=void 0,Va=function(a){if(!Eb){var b=function(){var a=K.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Eb.length;a++)w(Eb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;bb(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Eb.length;a++)w(Eb[a])}))})}};Eb=[];K.body?b():w(b)}Eb.push(a)},pb=function(){var a;a="www.googletagmanager.com/gtm.js";for(var b="https://"+a,c="http://"+a,d=1,e=K.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if(ag(g,c))return 3;1===d&&ag(g,b)&&(d=2)}}return d};
var rb=function(a){var b="www.googletagmanager.com/gtm.js?id="+encodeURIComponent(a)+"&l=dataLayer";u(x("https://","http://",b),void 0,void 0)};var xb=function(a,b,c){a instanceof Uh&&(a=a.resolve(Wh(b,c)),b=Mf);return{hb:a,w:b}};var ri=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),si={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},ti={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ui=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Qg=function(a){var b=Z("gtm.whitelist");
var c=b&&ui(Rf(b),si),d=Z("gtm.blacklist")||Z("tagTypeBlacklist")||[];ri.test(y.location&&y.location.hostname)&&(d=Rf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&ui(Rf(d),ti),f={};return function(g){var h=g&&g[Za];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Pf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Pf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Pf(e,h.a)))a:{for(var r=h.b||[],t=new Sf,v=0;v<e.length;v++)t.set(e[v],!0);for(v=0;v<r.length;v++)if(t.get(r[v])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _sel=function(a){return fa(a[Le])};_sel.a="sel";_sel.b=["customScripts"];var _eu=function(a){var b=String(Z("gtm.elementUrl")||a[Xc]||""),c=T(b);return b};_eu.a="eu";_eu.b=["google"];var zi=function(a,b){this.h=a;this.s=b};zi.prototype.toString=function(){var a=""+this.h;1<this.s&&(a=a+"-"+this.s);return a};var Ai=function(a,b){this.vb=a;this.La=b};Ai.prototype.toString=function(){return""+this.La+"."+this.vb};var Di=function(a,b){var c=new Bi(null,a,b);Ci(c);return c},Bi=function(a,b,c){this.Pb=Math.floor(Y().getTime()/864E5);this.Ja=b||"auto";this.ta=c||"/";var d=yh(this.Ja),e=zh(this.ta);this.N=a||new zi(d,e);this.m=[];this.I=new Sf},Fi=function(a,b,c){b&&(""==c.vb?Ei(a,b):(a.I.contains(b)||a.m.push(b),a.I.set(b,c)))},Gi=function(a,b){for(var c=0;c<b.length;c++)Fi(a,b[c][0],b[c][1])},Ei=function(a,b){var c=Pf(a.m,b);0<=c&&a.m.splice(c,1);a.I.set(b,void 0)},Hi=function(a){for(var b=[],c=0;c<a.m.length;c++){var d=
a.m[c];b.push([d,a.I.get(d)])}return b},Ii=function(a){for(var b=0,c=0;c<a.m.length;c++)b=Math.max(b,a.I.get(a.m[c]).La);return 864E5*b};Bi.prototype.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];a.push(""+c+"."+this.I.get(c).toString())}return"GAX1."+this.N.toString()+"."+a.join("!")};
var Ji=function(a,b){for(var c=new Date,d=zh(a.ta),e=[],f=0;f<a.m.length;f++){var g=a.m[f];a.I.get(g).La<a.Pb&&e.push(g)}for(f=0;f<e.length;f++)Ei(a,e[f]);if(a.m.length>(b||10))return!1;c.setTime(Ii(a));if("auto"!=a.Ja)return xh("_gaexp",a.toString(),a.ta,a.Ja,c);for(var h=wh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.N=new zi(yh(h[k]),d),xh("_gaexp",a.toString(),a.ta,h[k],c)))return!0;return!1},Ci=function(a){for(var b=a.N.h,c=a.N.s,d=Fa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Ki(a,d[f]);g&&e.push(g)}bg(e,
function(a,d){var e=a.N,f=d.N;return e.h==f.h&&e.s==f.s?!1:e.h==b&&e.s==c?!0:f.h==b&&f.s==c?!1:e.h==b?f.h!=b||e.s<f.s:f.h==b?!1:e.s==c?f.h!=b&&(f.s!=c||e.h<f.h):f.s==c?!1:e.h<f.h||e.h==f.h&&e.s<f.s});a.N=0<e.length?e[0].N:new zi(b,c);for(f=e.length-1;0<=f;f--)Gi(a,Hi(e[f]))},Ki=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ba(e[0]);if(0!=f.length){var g=2==e.length?Ba(e[1]):"1";if(Of(f)&&Of(g)){d=new zi(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new Bi(d,a.Ja,a.ta),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Of(m[1]))return;Fi(h,m[0],new Ai(m[2],W(m[1])))}}return h}}};var _exs=function(a){var b;var c=Di(a[zc],a[Cc]),d=a[sd];if(d){var e=c.I.get(d);b=e?e.vb:""}else b="";return b};_exs.a="exs";_exs.b=["google"];var _gaoo_c=function(a){if(a[Hf])return!0;var b=window._gaUserPrefs;if(b&&b.ioo&&b.ioo())return!0;try{var c=window.external;if(c&&"oo"==c._gaUserPrefs)return!0}catch(d){}return!!window["ga-disable-"+a[Pb]]};_gaoo_c.a="gaoo_c";_gaoo_c.b=["google"];var _f=function(a){var b=String(Z("gtm.referrer")||K.referrer);if(!b)return b;var c=T(b);return b};_f.a="f";_f.b=["google"];var _uv=function(){};_uv.a="uv";_uv.b=["google"];var Oi=function(a){var b=y.location,c;(c=a[Mc]?a[Mc]:Z("gtm.url"))&&(b=T(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);return f},_u=Oi;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Zb])==String(a[$b])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[$b],a[Gd]?"i":void 0)).test(a[Zb])};_re.a="re";_re.b=["google"];
var ej=function(a,b,c){var d,e,f=a.ownerDocument||a.document||document;"after"==c?(d=a.parentNode,e=a.nextSibling):"insert"==c?(d=a,e=a.firstChild):"append"==c?(d=a,e=null):(d=a.parentNode,e=a);if(!d||d==f)return{result:1,bd:[]};var g=cj(b,d);dj(g,"SCRIPT");dj(g,"NOSCRIPT");var h=[];if(g.firstChild)for(var k=g.firstChild;k;){var l=k.nextSibling;h.push(k);d.insertBefore(k,e);k=l}var m=a.nextSibling;"replace"==c&&d.removeChild(a);return{result:function(){for(;0<h.length;)d.removeChild(h.pop());"replace"==
c&&d.insertBefore(a,m)},bd:h.slice()}},fj={Ed:[1,'<select multiple="multiple">',"</select>"],Bd:[1,"<fieldset>","</fieldset>"],Cd:[1,"<map>","</map>"],Dd:[1,"<object>","</object>"],Gd:[1,"<table>","</table>"],Hd:[2,"<table><tbody>","</tbody></table>"],Ad:[2,"<table><colgroup>","</colgroup></table>"],Id:[3,"<table><tbody><tr>","</tr></tbody></table>"]},cj=function(a,b){var c=0,d="",e="",f=fj[b.tagName];null!=f&&(c=f[0],d=f[1],e=f[2]);var g=document.createElement("div");g.innerHTML=d+(a||"")+e;for(var h=
g;0<c;){var k=h.firstChild;if(!(k instanceof Element))return document.createElement("div");h=k;c--}return h},dj=function(a,b){for(var c=a.getElementsByTagName(b),d=[],e=c.length-1;0<=e;e--){var f=c[e];f.parentNode.removeChild(f);d.push(f)}};
var lj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=ij(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=jj(f,g);kj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},mj=null,ij=function(a){if(mj)return mj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return mj=
c}0==a.styleSheets.length&&a.createStyleSheet();return mj=a.styleSheets[0]},jj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},kj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};
var nj=function(a,b,c,d){if(a.style.setProperty)try{var e=a.style.getPropertyValue(b),f=a.style.getPropertyPriority(b);a.style.setProperty(b,c,d?"important":"");return function(){a.style.setProperty(b,"",f);a.style.setProperty(b,e,f)}}catch(h){}var g=a.style.cssText;a.style.cssText+=";"+(b+": "+c+(d?" !important":""))+";";return function(){a.style.cssText=g}};var tj={},uj=void 0,vj=function(a){var b=tj[a];b||(b={id:a,A:[],oa:0,Bb:null,kb:void 0,qb:!1},tj[a]=b);uj=b},xj=function(a,b,c,d){var e=uj;if(!Ah||!e)return!1;var f={id:e.id+":"+e.A.length,vc:b,ea:[],qc:c,O:a,Ya:0,Ta:d||null,Ob:0,na:!1};e.A.push(f);null===a?(f.na=!0,b(null)):wj(e);return!0},yj=function(a){var b=lj(a,"visibility","hidden",!0);return function(){R(b)&&b.apply();b=null}},zj=function(a,b,c,d){var e=b;if(!hg){var f=yj(a.F);ig.push(f);e=function(a,c){var d=b(a,c);f();return d}}return xj(a,
e,c,d)},wj=function(a){if(!a.qb){for(var b=a.oa;b<a.A.length;b++){var c=a.A[b],d=b==a.oa;if(!c.na&&!Aj(d,c))break;c.na&&d&&a.oa++}a.A.length>a.oa?(a.Bb||(a.Bb=y.setTimeout(function(){a.Bb=null;wj(a)},80)),hg||a.kb||(a.kb=function(){w(function(){wj(a)})},va(K,"DOMContentLoaded",a.kb))):Bj(a)}},Bj=function(a){for(var b=0;b<a.A.length;b++){var c=a.A[b];if(c.O)for(var d=fa(c.O.F)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Cj(f,c.id),c.ea.push(Dj(f,c.id)))}}},
Aj=function(a,b){var c=[];if(b.O){var d=Ej(b.O,b.id),e=null;b.Ta&&(e=Ej(b.Ta,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!hg&&(null===b.Ta.v||b.Ob+c.length<b.Ta.v)))break;c.push({element:g,td:h})}}if(!hg&&b.qc&&(!a||null==b.O.v||b.O.v!=b.Ya+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].td,n;b.Ya++;Cj(l,b.id);m&&(b.Ob++,n=b.id+"-t",Cj(m,n));var p=b.vc(l,m);R(p)&&b.ea.push(p);b.ea.push(Dj(l,b.id));m&&n&&b.ea.push(Dj(m,n))}if(b.O.v&&
b.O.v==b.Ya||hg)b.na=!0;return!0},Cj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Dj=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ej=function(a,b){for(var c=fa(a.F)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.M&&!Fj(f))break;d.push(f)}}return d},Fj=function(a){if(hg)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var _dr=function(a,b,c){var d=a[vf],e=a[Qb],f=Z("optimize.experimentCallback"),g=a[sd],h=a[td];if(R(f)){var k={xid:g,xvar:h,activate:e};try{f(k)}catch(v){}}if(e){var l;var m=tj[d];if(m){for(var n=m.oa=0;n<m.A.length;n++)m.A[n].na=!1;wj(m);l=!0}else l=!1;if(l){c();return}vj(d)}else{var p=tj[d];if(p&&!p.qb){for(;p.A.length;)for(var r=p.A.pop();r.ea.length;){var t=r.ea.pop();if(R(t))try{t()}catch(v){}}p.qb=!0;delete tj[d]}}b()};_dr.a="dr";_dr.b=["google"];var _ec=function(a,b,c){var d=a[hd],e=a[Le],f=a[Ed],g=a[ee],h=a[Fc],k=a[Tb];!1!==k&&(k=!0);var l=a[$e];!uj&&l&&vj(l);if(!Zf(d)){if(!Ah){c();return}if(uj){zj({F:e,M:!0,v:e==h?1:null},function(a){if(a)return ej(a,f,g).result},k)?b():c();return}d=fa(e)}for(var m=0;m<d.length;m++)ej(d[m],f,g);b()};_ec.a="ec";_ec.b=["customScripts"];
var _est=function(a,b,c){var d=a[Ic],e=a[Kc],f=a[Gc],g=a[hd],h=a[Le],k=a[Fc],l=a[Hc],m=a[$e];!uj&&m&&vj(m);if(!Zf(g)){if(!Ah){c();return}if(uj){var n,p;if(a[Jc]){var r=lj(h,d,e,f,l),t={F:"body",M:!1,v:1};p=xj(t,function(){R(r)&&r.apply();r=null;return lj(h,d,e,f,l)},!1)}else t={F:h,M:!1,v:h==k?1:null},n=function(a){if(a)return nj(a,d,e,f)},p=zj(t,n,!1);p?b():c();return}if(a[Jc]){lj(h,d,e,f,l);b();return}g=fa(h)}for(var v=0;v<g.length;v++)nj(g[v],d,e,f);b()};_est.a="est";_est.b=["customScripts"];var _exsu=function(a,b,c){var d;var e=Di(a[zc],a[Cc]),f=a[sd],g=a[je],h=a[be],k=a[vd];if(f){void 0==g&&(g="");Fi(e,f,new Ai(g,a[ud]));var l;l=k||{};var m=0;l.hasOwnProperty("")&&Of(l[""])&&(m=e.Pb-W(l[""]));for(var n=0;n<e.m.length;n++){var p=e.m[n],r=p;if(l.hasOwnProperty(r)&&Of(l[r])){var t=e.I.get(p);t.La=W(l[p])+m;Fi(e,p,t)}}d=Ji(e,h)}else d=!1;d?b():c()};_exsu.a="exsu";_exsu.b=["google"];var _gag=function(a,b){hb("gaGlobal",{})[a[fe]]=a[Hf];b()};_gag.a="gag";_gag.b=["google"];var yk=function(a){if(!a)return!1;if(a[Yb]&&ab(a[$b])){for(var b=a[$b],c=0;c<b.length;c++)if(a[$b]=b[c],Tf(a))return!0;return!1}return Tf(a)};var zk=117,Ak=[],Bk=[],Rg=[],Ck=new Sf,Dk=[],Ek=[],ph=[],qh=[],Fk=function(){this.U=[]};Fk.prototype.set=function(a,b){this.U.push([a,b]);return this};Fk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.U.length;d++){var e=Ug(this.U[d][0],a,b),f=Ug(this.U[d][1],a,b);c[e]=f}return c};var Gk=function(a){this.index=a};Gk.prototype.resolve=function(a,b){var c=Rg[this.index];if(c&&!b(c)){var d=c[$a];if(a){if(a.get(d))return;a.set(d,!0)}c=Ug(c,a,b);a&&a.set(d,!1);return Tf(c)}};
var _M=function(a){return new Gk(a)},Hk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Ug(Ak[a[f]],b,c);g===lb&&(e=!0);d.push(g)}return e?new Uh(d):d.join("")}},_T=function(a){return new Hk(arguments)},Ik=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Ug(a[0],c,d);if(a[0]instanceof Gk&&b(8)&&b(16)){if(e===lb)return e;var f=Ka();Ck.set(f,e);return'google_tag_manager["'+Ha.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=dk[a[g]](e);return e}},_E=function(a,b){return new Ik(arguments)},Jk=function(a,b){this.D=a;this.xa=b},_R=function(a,b){return new Jk(a,b)};
var Ug=function(a,b,c){var d=a;if(a instanceof Gk||a instanceof Fk||a instanceof Hk||a instanceof Ik)return a.resolve(b,c);if(!(a instanceof Jk))if(ab(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Ug(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Ug(a[f],b,c))}return d},Mk=function(){for(var a=[_eq,__e,'_event','1',_M(0),__dee,'Experiment_GTM-W69N8TP_OPT-NSNXT 4',_M(1),'','8000488_1','__serverSideCookieCheckFor_Experiment_GTM-W69N8TP_OPT-NSNXT 12','UA-25136408-1',true,_gaoo_c,'Experiment_GTM-W69N8TP_OPT-NSNXT 12',_M(2),_M(3),'8000488_0',_gag,'Experiment_GTM-W69N8TP_OPT-NSNXT','vid','Experiment_GTM-W69N8TP_OPT-NSNXT 14',_M(4),0,_exsu,'GTM-W69N8TP_OPT-NSNXT',_M(5),'Experiment_GTM-W69N8TP_OPT-NSNXT 26',_M(6),_T(28),17782,'Experiment_GTM-W69N8TP_OPT-NSNXT 8',_M(7),2,'Experiment_GTM-W69N8TP_OPT-NSNXT 22',_sel,'Experiment_GTM-W69N8TP_OPT-NSNXT 24',':root',_M(9),'null',__ctto,'Experiment_GTM-W69N8TP_OPT-NSNXT 10',_M(10),false,_exs,'Experiment_GTM-W69N8TP_OPT-NSNXT 28',_M(11),_re,__u,'Page URL','URL',_M(12),'optimize$','Experiment_GTM-W69N8TP_OPT-NSNXT 20','8000488_4','8000488_5',_uae,_R(1,1),[57],4,__gthc,'Experiment_GTM-W69N8TP_OPT-NSNXT 18',_M(14),'8000488_2','8000488_3',_ua,_uv,'Experiment_GTM-W69N8TP_OPT-NSNXT 6',_M(15),'auto','title','anonymizeIp','adSenseId','language','encoding','screenColors','screenResolution','viewportSize','flashVersion','referrer','location',{70:8,71:3,72:68,73:68,74:68,75:68,76:68,77:68,78:68,79:68,80:68},'Experiment_GTM-W69N8TP_OPT-NSNXT 16',_M(16),'\x26tid','\x26t','\x26ni','\x26dt','data',{84:11,85:88,86:12,87:68,70:8,71:3,72:68,73:68,74:68,75:68,76:68,77:68,78:68,79:68,80:68},6,_ol,_R(5,1),[92],'8000488_8','8000488_9','blacklisted_behavior','failed_behavior','tag_reference','BLACKLISTED_DISABLE','FAILED_ABORT',_R(6,0),{96:99,97:100,98:101},_R(7,0),{96:99,97:100,98:103},[102,104],16,_dr,'Experiment_GTM-W69N8TP_OPT-NSNXT:0',8,_est,'max-width','700px','.subheader','h3.ctaHeader',10,_ec,'replace','\x3cdiv class\x3d\x22grid-col-12 grid-col--center grid-col--align-center\x22 style\x3d\x22\x22\x3e\n        \x3ch1 style\x3d\x22\x22\x3eThe Leaders in Online Coding Courses\x3c/h1\x3e\n  \t\t\x3ch5 class\x3d\x22subheader\x22\x3e Whether you’re writing your first line of code or transforming your career, start with us and get the technical skills you need to skill up and stand out.\x3c/h5\x3e\n      \x3c/div\x3e','article.top-section\x3earticle\x3ediv:nth-of-type(1)\x3ediv',12,__c,false,'1656455650.1521745894','r1fscc-fQSWA7f0DdivnHA',1,{127:128,129:130},'',17612,'r1fscc-fQSWA7f0DdivnHA',17683,true,true,false],b=[],c=0;c<a.length;c++)b[c]=
Lk(c,a);return b},Lk=function(a,b){var c=b[a],d=c;if(c instanceof Gk||c instanceof Ik||c instanceof Hk||c instanceof Jk)d=c;else if(ab(c)){d=[];for(var e=0;e<c.length;e++)d[e]=Lk(c[e],b)}else if("object"==typeof c){d=new Fk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],Lk(c[f],b))}return d},Ok=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Ak[e[1]]);if(1==a){var f=Nk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=Bk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=Nk(e[g]);3==a&&(c[d]=Ak[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ak[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Nk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<zk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Pk=function(a,b,c){a.push.apply(a,Ok(b,c))};var Qk;
var Tg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=Tk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},Wk=function(a){},Xk=function(a,b){},Wg=function(a){};var Yk,Zk,$k;var ml=function(a,b){return function(){}},nl=function(a,b){return function(){}};var ol=function(a){var b=this;this.i=a;this.la=this.hc=!1;this.Sa=[];this.Ma=[];this.w=function(){b.la||Xf(b.Sa);$f(b,1);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().w()};this.C=function(){b.la||Xf(b.Ma);$f(b,2);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().C()};this.H=Mf},pl=function(a,b){a.Sa.push(b)},ql=function(a,b){a.Ma.push(b)},rl=function(a){this.P=[];this.xb=[];this.Rb={};this.Xb=[];this.ba=0;this.ub={};this.zb={};this.yb={};this.event=a};rl.prototype.addListener=function(a){this.Xb.push(a)};
var sl=function(a){0<a.ba||Xf(a.Xb)},tl=function(a,b,c,d,e,f){if(!c.la){a.P[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=ab(d)?d.slice():["or",d];e=ab(e)?e.slice():[e];f=ab(f)?f.slice():[f];a.Rb[b]=d;a.ub[b]=0<e.length;a.zb[b]=0<f.length;a.ba++;var g=function(){0<a.ba&&!a.ub[b]&&!a.zb[b]&&a.ba--;sl(a)};pl(c,g);ql(c,g)}},yl=function(a){for(var b=[],c={},d=0;d<a.P.length;c={W:c.W},d++)if(c.W=a.P[d],c.W){var e=a.Rb[d],f=a.ub[d],g=a.zb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=
ul(e,c.W.H),k=0;k<e.length;k++)e[k]instanceof Jk&&e[k].D!=d&&vl(a,e[k].D,h);(f||g)&&wl(a,d,function(a){return function(){0<a.W.G.ba&&a.W.G.ba--;sl(a.W.G)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.P[b[d]].H();for(d=0;d<a.xb.length;d++){var l=a.xb[d];xl(l);0<l.length&&l[0].H()}},vl=function(a,b,c){a.P[b]&&(pl(a.P[b],function(){c(b,!0)}),ql(a.P[b],function(){c(b,!1)}))},ul=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Jk&&a[g].D===d||a[g]===d){f=
g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},wl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Ek[b];if(a.event.g(h)){}else g=zl(h,b,a.event.g,a);if(c=g){var k=Al(b,!0);0<k.length&&f(k[0].D);d.push(c);var l=Al(b,!1);0<l.length&&f(l[0].D)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Al(h.i,!0);if(0<k.length){var l=d[g-1],m=Bl(h);pl(l,m);0==k[0].xa?ql(l,m):ql(l,c)}var n=Al(h.i,!1);0<n.length&&(m=Bl(d[g+1]),pl(h,m),0==n[0].xa?ql(h,m):ql(h,c))}pl(d[d.length-1],c);ql(d[d.length-1],c);a.xb.push(d)}},Al=function(a,b){var c=b?Pe:ff,d=Ek[a],e=void 0===d[c]?[]:d[c];return ab(e)?e:[e]},Bl=function(a){return function(){a.H()}},xl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Mb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.G.yb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Al(a[c+1].i,!0);if(0<h.length&&1==h[0].xa)for(++c;c<a.length;c++)b.push(a[c])}}var k=Cl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],r=p[0],t=p[p.length-1],v,z=0;z<a.length;z++){var J=a[z];!m&&J.i==r&&0<z&&(m=a[z-1]);J.i==t&&z<a.length-1&&(n=a[z+1]);if(-1<Pf(p,J.i))if(v=a.splice(z,1)[0],J.i==t)break;else z--}if(v){var F=Number(l),E=m,L=n;if(E){var B=E.Sa[0],D=E.Ma[0],A=E;A.Sa=[];A.Ma=
[];pl(E,B);ql(E,D)}if(E&&L){var C=Bl(L);pl(E,C);var H=Al(E.i,!1);0<H.length&&H[0].D!=F&&0==H[0].xa&&ql(E,C);var I=Al(L.i,!0);0<I.length&&I[0].D!=F&&0==I[0].xa&&ql(E,C)}}}},Cl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Al(a,!0);0<b.length&&f(b[0].D);e.push(a);var c=Al(a,!1);0<c.length&&f(c[0].D)};f(d.i);b[d.i]=e}Dl(a,b);return b},Dl=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Pf(b[e],d)){delete b[d];break}}};var El=function(a,b,c){return function(){a[Ad]=b.w;a[Bd]=b.C;var d=b.i,e=b.G&&b.G.yb[d],f=Mb[d]&&Mb[d].state,g=e?void 0!==e:b.hc||b.la,h=Mb[d]&&Mb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){$f(b,0);var m=b.G?b.G.event:void 0;a=Ug(a,new Sf,c);if(m){}Tf(a,b.w,b.C)}else k&&0==f||l&&0==e?Nb[d].push(b):k&&1==f||l&&1==e?b.w():b.C()}},zl=function(a,b,c,d){function e(a){return a.i===b}var f=function(){var a=d&&d.P;return a&&Qf(a,e)}()||new ol(b);if(f.G=d)pl(f,ml(d.event.id,a)),ql(f,nl(d.event.id,a));f.H=El(a,f,c);return f};
var Fl=function(a,b,c,d,e){this.list=a;this.context=b;this.g=c;this.w=d;this.C=e};Fl.prototype.H=function(a){if(a>=this.list.length)this.w();else{var b=this.list[a].tag_reference.D,c=Ek[b];c[$e]=this.context;c[af]=a;var d=this,e=zl(c,b,this.g);pl(e,function(){d.Fa(a,!0)});ql(e,function(){d.Fa(a,!1)});e.H()}};Fl.prototype.Fa=function(a,b){if(!b)switch(this.list[a].failed_behavior){case "FAILED_ABORT":this.C();return}this.H(a+1)};var Gl=function(a,b,c){var d=a[Ze];if(d){var e=a[$a]||Gl.a+Math.random(),
f=S("gtm.uniqueEventId")||0,g=Jg(f),h=Qg(g.isWhitelisted);a:{for(var k=d,l=[],m=0;m<k.length;m++){var n=k[m];if(h(Ek[n.tag_reference.D]))switch(n.blacklisted_behavior){case "BLACKLISTED_DISABLE":d=[];break a;case "BLACKLISTED_IGNORE":continue;case "BLACKLISTED_ABORT":d=l;break a}else l.push(n)}d=l}(new Fl(d,e,h,b,c)).H(0)}else c()},_ol=Gl;_ol.a="ol";_ol.b=["google"];
var Il=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];y[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&t[e]||!c&&void 0===t[e])){var f=v[e]?Oa(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}hb("GoogleAnalyticsObject",a[fe]||"ga");var l=function(){return y.GoogleAnalyticsObject},m=hb(l(),function(){var a=y[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(Y());var n="",p="";"string"!=typeof a[tf]?(p=Ka(),n=p+"."):""!==
a[tf]&&(p=a[tf],n=p+".");var r=!1;
var z={name:p};void 0!==a[zc]&&(z.cookieDomain=a[zc]);m("create",a[Pb],z);d("set","&gtm",ya(!0));e("nonInteraction",ke);
e("title",nf);var F;F=a[Dd];d("set","hitCallback",function(){if(R(a[Cd]))a[Cd]();else{var c=a[wd],d=c&&c.hitCallback;R(d)&&d()}b()});if(a[pf]){}else if(a[qf]){}else if(a[sf]){}else if(a[rf]){}else if(a[Vc]){}else if(a[Tc]){}else if(a[of]){
F?d("send","data",F):d("send","data");}else{a[ld]&&(d("require","ec","ec.js"),h());F?d("send","pageview",F):d("send","pageview");}if(!Il){var N=a[Rc]?"u/analytics_debug.js":"analytics.js";a[Kd]&&!a[Rc]&&(N="internal/"+N);Il=
!0;u(ib("https:","http:","//www.google-analytics.com/"+N,r),function(){y[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var _uae=function(a,b){var c=hb("gaData",{}),d=a[Pb],e=a[sd],f=a[td];if(d){c[d]=c[d]||{};var g=c[d];g.pending_experiments=g.pending_experiments||{};g.pending_experiments[e]=f;g.experiments=g.experiments||{};g.experiments[e]=f}var h=Oa("false");d&&h||(c.expId=e,c.expVar=f);b()};_uae.a="uae";_uae.b=["google"];var Ll=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Dk[b]&&Ug(Dk[b],new Sf,c),e=d;d&&(e=yk(d));a[b]=[e,d]}return a[b]}},Ml=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.aa(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.aa(e[d],a.g)[0])return!1;return!0},Nl=!1;
Kg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Nl)return!1;Nl=!0;break;case "gtm.sync":if(Z("gtm.snippet")!=Jb)return!1}for(var f={id:a,name:b,Fa:d||Mf,ja:Nk(),Qa:Nk(),aa:Ll(),g:Qg(c)},g=[],h=0;h<ph.length;h++)if(Ml(f,ph[h])){g[h]=!0;for(var k=f,l=ph[h],m=l[1],n=0;n<m.length;n++)k.ja[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Qa[p[n]]=!0}else g[h]=!1;for(var Q=[],M=0;M<zk;M++)if(f.ja[M]&&
!f.Qa[M])if(f.g(Ek[M])){}else Q[M]=Ek[M];f.ua=Q;for(var ma=new rl(f),da=0;da<zk;da++)if(f.ja[da]&&!f.Qa[da])if(f.g(Ek[da])){}else{var Ma=f.ua[da],Qj=zl(Ma,da,f.g,ma);tl(ma,da,Qj,Ma[Yc],Ma[Pe],Ma[ff]);if(Ma[Ob])break}ma.addListener(f.Fa);yl(ma);sl(ma);
e&&R(e)&&e({passingRules:g,resolvedTags:f.ua});if("gtm.js"==b||"gtm.sync"==b)a:{}var Pj={cl:!0,evl:!0,fsl:!0,hl:!0,jel:!0,lcl:!0,sdl:!0,tl:!0,ytl:!0},Ld;for(Ld in f.ua)if(f.ua.hasOwnProperty(Ld)&&!Pj[f.ua[Ld][Za].a.replace(/_/g,"")])return!0;return!1};var Pl=function(){};var Ql={};var Vl=function(){};var Ol={macro:function(a){if(Ck.contains(a))return Ck.get(a)}};Ol.dataLayer=yg;Ol.onHtmlSuccess=Xh(!0);Ol.onHtmlFailure=Xh(!1);Ol.callback=function(a){kb.hasOwnProperty(a)&&R(kb[a])&&kb[a]();delete kb[a]};
Ol.Dc=function(){var a=y.google_tag_manager;a||(a=y.google_tag_manager={});sb=a;if(a[Ha.f]){var b=sb.zones;b&&b.unregisterChild(Ha.f)}else{a[Ha.f]=Ol;ii();th();Ak.push.apply(Ak,Mk());Pk(Bk,0,"17:0,17:1,20:2,41:3,4:4,17:5,20:6,5:7,20:10,0:11,17:13,20:14,40:15,4:16,5:12,17:18,20:19,21:12,23:20,20:21,40:22,32:23,17:24,26:12,14:25,13:26,20:27,28:23,24:29,16:30,20:31,15:32,32:33,20:34,17:35,20:36,29:37,4:38,5:39,17:40,20:41,4:42,5:43,17:44,20:45,4:46,5:8,17:47,17:48,20:49,42:50,4:51,5:52,20:53,17:56,31:58,27:12,12:29,32:59,17:60,20:61,43:11,4:62,5:23,17:65,37:12,3:12,25:12,17:66,20:67,36:68,6:69,18:81,20:82,38:83,2:89,32:90,17:91,31:93,34:8,35:23,33:105,32:106,17:107,39:108,1:12,32:109,17:110,9:111,11:112,29:113,10:12,8:43,7:114,32:115,17:116,22:117,19:118,29:119,7:119,32:120,17:121,44:122,17:121,44:123,17:121,44:124,17:121,44:125,17:121,44:126,17:121,44:131,17:121,44:132,17:121,44:133");Pk(Rg,1,"O,oB,AMAAAAAAAAAAAAAAgB,A4B,AAACAAAAAAAAAAAAAG,AAQABAAAAAAAAAAAAY,AAAANAAAAAAAAAAAAgB,AAAAABAAAAAAAAAAAAG,AAAABIAAAAAAAAAAAAY,AAAAAwB,IAAAAAY,AAAACAAG,IAAAAAAAH,AAAABAAAgAAAAAAAAAgB,IAAAAAAAAgD,AAAAAAAAAAAM,AAAAAAAAAAAACAAAAAAG");Pk(Dk,1,"RC,BAG,BAAAAAG,BAAAAAgB,BAAAAAAY,AAAAAAAgY,BAAAAAAAAAM");Pk(Ek,1,"AAoN,AAAwyG,AIgACAAAAf,AIAAAAAAAGwzd,AAAAAAAAAAAAgf,AAAgCAAAAKAAAgH,AAAAAAAAAAAAAA4f,AAAAAAAAAAAAAAAgf");Pk(ph,2,"B:B::,p:U:U:,p:U:E:,p:I:UB:,p:I:EB:,C:::f");Pk(qh,4,"9:,54.94:,55.95:,63:,64:,:17.17.17.17.17");for(var c=0;c<Ek.length;c++){var d=Ek[c],e=1;d[me]?e=2:
d[yf]&&(e=0);Mb[c]={firingOption:e,state:void 0};Nb[c]=[]}Hg();Zg();var n=y;if("interactive"==K.readyState&&!K.createEventObject||"complete"==K.readyState)jg();else{va(K,"DOMContentLoaded",jg);va(K,"readystatechange",jg);if(K.createEventObject&&K.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(J){}p&&lg()}va(n,"load",jg)}"complete"===K.readyState?qg():va(y,"load",qg);a:{}Vl();Pl();a:{}}};Ol.Dc();var _vs="res_ts:1521731532390000,srv_cl:189307786,ds:live,cv:25";
})()
